### ISSUE TITLE
App doesn't work.

### ISSUE THREAD

**Issue by zer0xtgs** [shahbazahmed1269/AndroidGithubIssues#4]
Hello, I have compiled the app but it doesn't work. I have entered a repo name, but it does nothing.
Logcat shows this:
03-12 14:20:46.943 16719-16719/example.com.githubissues W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
03-12 14:20:46.944 16719-16719/example.com.githubissues W/IInputConnectionWrapper: finishComposingText on inactive InputConnection

**Comment by shahbazahmed1269** [comment]
which branch are you building the app from and what input did you enter?

**Comment by zer0xtgs** [comment]
Thx for fast response, I have tried Master and branch with DI. I entered square/retrofit into input text, pressed enter and nothing happened.
![android emulator - nexus_5x_api_24 5554 2018-03-12 17-20-42](https://user-images.githubusercontent.com/14161904/37292695-194fc778-261a-11e8-8fc2-8ba4945fa7a4.png)

**Comment by shahbazahmed1269** [comment]
Thats odd because both the branches work in my machine.
Here is the snapshot of master branch. Try clean build and reinstalling the app. Maybe try it on a different device (physical or emulator).  

<img width="1154" alt="screen shot 2018-03-12 at 9 06 58 pm" src="https://user-images.githubusercontent.com/10626910/37293649-f0d97134-2639-11e8-9712-e418f4171bb2.png">

Can you help me replicate it? If there's any issue I'll look into it.

**Comment by zer0xtgs** [comment]
I have run the app on my physical device and it works properly, looks like something wrong with my emulator. But I don't know how u can replicate the same bug.

**Comment by shahbazahmed1269** [comment]
In that case I am closing this issue.
